#!/usr/bin/python
import time
from stepper import Stepper
from button import Button
from servo import Servo
from arm import Arm
# Stepper Setup
steppers = []
steppers.append(Stepper())
steppers.append(Stepper(enable_p = "P8_10", step_p = "P8_11", dir_p = "P8_12"))
steppers.append(Stepper(enable_p = "P8_14", step_p = "P8_15", dir_p = "P8_16"))
steppers.append(Stepper(enable_p = "P8_17", step_p = "P8_18", dir_p = "P8_19"))
for stepper in steppers:
    stepper.setup()
    stepper.set_rpm(300)
# Servo Setup
servos = []
servos.append(Servo())
servos.append(Servo(pin = "P8_21"))
servos.append(Servo(pin = "P8_22"))
servos.append(Servo(pin = "P8_23"))
# Button Setup
buttons = []
buttons.append(Button())
buttons.append(Button("P8_25"))
buttons.append(Button("P8_26"))
buttons.append(Button("P8_27"))
while True:
    for i in range(2000):
        for stepper in steppers:
            stepper.step()
    print("Change Places!")
    for stepper in steppers:
        stepper.forwards = not stepper.forwards
    

